# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-24 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_auto_20190624_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
